name = "url-rewriter"
type = "javascript"
compatibility_date = "2021-10-27"

[dev]
port = 9001
local_protocol="http"
upstream_protocol="https"

[env.staging]
name = "staging-rewriter"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-rewriter"
vars = { ENVIRONMENT = "production" }
route = "http.erfianugrah.com/*"